repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.2
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        files: ^backend/app/
      - id: ruff-format
        files: ^backend/app/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: detect-private-key
      - id: check-yaml
      - id: check-ast
      - id: check-json
      - id: check-toml

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        name: Detect secrets
        language: python
        entry: detect-secrets-hook
        args:
          - --exclude-files
          - '(alembic\.ini|migrations/versions/.*)'

  - repo: https://github.com/crate-ci/typos
    rev: v1.32.0
    hooks:
      - id: typos
        files: ^backend/app/

# Optional: uncomment and configure if you want Pyright
#  - repo: https://github.com/RobertCraigie/pyright-python
#    rev: v1.1.402
#    hooks:
#      - id: pyright
#        files: ^backend/app/
